ara/views/about.py
#   Copyright 2017 Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

from ara import models
from ara.utils import fast_count
from flask import Blueprint
from flask import current_app
from flask import render_template

about = Blueprint('about', __name__)


@about.route('/')
def main():
    """ Returns the about page """
    if current_app.config['ARA_PLAYBOOK_OVERRIDE'] is not None:
        override = current_app.config['ARA_PLAYBOOK_OVERRIDE']
        files = (models.File.query
                 .filter(models.File.playbook_id.in_(override)))
        host_facts = (models.HostFacts.query
                      .join(models.Host)
                      .filter(models.Host.playbook_id.in_(override)))
        hosts = (models.Host.query
                 .filter(models.Host.playbook_id.in_(override)))
        playbooks = (models.Playbook.query
                     .filter(models.Playbook.id.in_(override)))
        records = (models.Data.query
                   .filter(models.Data.playbook_id.in_(override)))
        tasks = (models.Task.query
                 .filter(models.Task.playbook_id.in_(override)))
        task_results = (models.TaskResult.query
                        .join(models.Task)
                        .filter(models.Task.playbook_id.in_(override)))
    else:
        files = models.File.query
        host_facts = models.HostFacts.query
        hosts = models.Host.query
        playbooks = models.Playbook.query
        records = models.Data.query
        tasks = models.Task.query
        task_results = models.TaskResult.query

    return render_template('about.html',
                           active='about',
                           files=fast_count(files),
                           host_facts=fast_count(host_facts),
                           hosts=fast_count(hosts),
                           playbooks=fast_count(playbooks),
                           records=fast_count(records),
                           tasks=fast_count(tasks),
                           task_results=fast_count(task_results))

ara/views/file.py
#   Copyright 2017 Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

from ara import models
from flask import abort
from flask import Blueprint
from flask import current_app
from flask import render_template

file = Blueprint('file', __name__)


@file.route('/')
def index():
    """
    This is not served anywhere in the web application.
    It is used explicitly in the context of generating static files since
    flask-frozen requires url_for's to crawl content.
    url_for's are not used with file.show_file directly and are instead
    dynamically generated through javascript for performance purposes.
    """
    if current_app.config['ARA_PLAYBOOK_OVERRIDE'] is not None:
        override = current_app.config['ARA_PLAYBOOK_OVERRIDE']
        files = (models.File.query
                 .filter(models.File.playbook_id.in_(override)))
    else:
        files = models.File.query.all()

    return render_template('file_index.html', files=files)


@file.route('/<file_>/')
def show_file(file_):
    """
    Returns details of a file
    """
    file_ = (models.File.query.get(file_))
    if file_ is None:
        abort(404)

    return render_template('file.html', file_=file_)

ara/views/host.py
#   Copyright 2017 Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

import json
import six

from ara import models
from flask import abort
from flask import Blueprint
from flask import current_app
from flask import render_template

host = Blueprint('host', __name__)


@host.route('/')
def index():
    """
    This is not served anywhere in the web application.
    It is used explicitly in the context of generating static files since
    flask-frozen requires url_for's to crawl content.
    url_for's are not used with host.show_host directly and are instead
    dynamically generated through javascript for performance purposes.
    """
    if current_app.config['ARA_PLAYBOOK_OVERRIDE'] is not None:
        override = current_app.config['ARA_PLAYBOOK_OVERRIDE']
        hosts = (models.Host.query
                 .filter(models.Host.playbook_id.in_(override)))
    else:
        hosts = models.Host.query.all()

    return render_template('host_index.html', hosts=hosts)


@host.route('/<id>/')
def show_host(id):
    try:
        host = models.Host.query.get(id)
    except models.NoResultFound:
        abort(404)

    if host and host.facts:
        facts = sorted(six.iteritems(json.loads(host.facts.values)))
    else:
        abort(404)

    return render_template('host.html',
                           host=host,
                           facts=facts)

ara/views/reports.py
#   Copyright 2017 Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

from ara import models
from ara import utils
from flask import abort
from flask import Blueprint
from flask import current_app
from flask import jsonify
from flask import redirect
from flask import render_template
from flask import url_for

reports = Blueprint('reports', __name__)


# This is a flask-frozen workaround in order to generate an index.html
# at the root of the generated report.
@reports.route('/index.html')
def main():
    return redirect('/')


@reports.route('/')
@reports.route('/reports/')
@reports.route('/reports/list/<int:page>.html')
def report_list(page=1):
    if current_app.config['ARA_PLAYBOOK_OVERRIDE'] is not None:
        override = current_app.config['ARA_PLAYBOOK_OVERRIDE']
        playbooks = (models.Playbook.query
                     .filter(models.Playbook.id.in_(override))
                     .order_by(models.Playbook.time_start.desc()))
    else:
        playbooks = (models.Playbook.query
                     .order_by(models.Playbook.time_start.desc()))

    if not utils.fast_count(playbooks):
        return redirect(url_for('about.main'))

    playbook_per_page = current_app.config['ARA_PLAYBOOK_PER_PAGE']
    # Paginate unless playbook_per_page is set to 0
    if playbook_per_page >= 1:
        playbooks = playbooks.paginate(page, playbook_per_page, False)
    else:
        playbooks = playbooks.paginate(page, None, False)

    stats = utils.get_summary_stats(playbooks.items, 'playbook_id')

    result_per_page = current_app.config['ARA_RESULT_PER_PAGE']

    return render_template('report_list.html',
                           active='reports',
                           result_per_page=result_per_page,
                           playbooks=playbooks,
                           stats=stats)


@reports.route('/reports/<playbook_id>.html')
def report(playbook_id):
    playbook = models.Playbook.query.get(playbook_id)
    if playbook is None:
        abort(404)

    stats = utils.get_summary_stats([playbook], 'playbook_id')

    result_per_page = current_app.config['ARA_RESULT_PER_PAGE']

    return render_template('report_single.html',
                           active='reports',
                           result_per_page=result_per_page,
                           playbook=playbook,
                           stats=stats)

# Note (dmsimard)
# We defer the loading of the different data tables and render them
# asynchronously for performance purposes.
# Because of this, we need to prepare some JSON data so data tables can
# retrieve it through AJAX:
#   https://datatables.net/examples/ajax/defer_render.html
# The following routes are there to support this mechanism.
# The routes have a text extension for proper mimetype detection.


@reports.route('/reports/ajax/parameters/<playbook>.txt')
def ajax_parameters(playbook):
    playbook = models.Playbook.query.get(playbook)
    if playbook is None:
        abort(404)

    results = dict()
    results['data'] = list()

    results['data'].append(['playbook_path', playbook.path])
    results['data'].append(['ansible_version', playbook.ansible_version])

    if playbook.options:
        for option in playbook.options:
            results['data'].append([option, playbook.options[option]])

    return jsonify(results)


@reports.route('/reports/ajax/plays/<playbook>.txt')
def ajax_plays(playbook):
    plays = (models.Play.query
             .filter(models.Play.playbook_id.in_([playbook])))
    if not utils.fast_count(plays):
        abort(404)

    jinja = current_app.jinja_env
    date = jinja.from_string('{{ date | datefmt }}')
    time = jinja.from_string('{{ time | timefmt }}')

    results = dict()
    results['data'] = list()

    for play in plays:
        name = u"<span class='pull-left'>{0}</span>".format(play.name)
        start = date.render(date=play.time_start)
        end = date.render(date=play.time_end)
        duration = time.render(time=play.duration)
        results['data'].append([name, start, end, duration])

    return jsonify(results)


@reports.route('/reports/ajax/records/<playbook>.txt')
def ajax_records(playbook):
    records = (models.Data.query
               .filter(models.Data.playbook_id.in_([playbook])))
    if not utils.fast_count(records):
        abort(404)

    jinja = current_app.jinja_env
    record_key = jinja.get_template('ajax/record_key.html')
    record_value = jinja.get_template('ajax/record_value.html')

    results = dict()
    results['data'] = list()

    for record in records:
        key = record_key.render(record=record)
        value = record_value.render(record=record)

        results['data'].append([key, value])

    return jsonify(results)


@reports.route('/reports/ajax/results/<playbook>.txt')
def ajax_results(playbook):
    task_results = (models.TaskResult.query
                    .join(models.Task)
                    .filter(models.Task.playbook_id.in_([playbook])))
    if not utils.fast_count(task_results):
        abort(404)

    jinja = current_app.jinja_env
    time = jinja.from_string('{{ time | timefmt }}')
    action_link = jinja.get_template('ajax/action.html')
    name_cell = jinja.get_template('ajax/task_name.html')
    task_status_link = jinja.get_template('ajax/task_status.html')

    results = dict()
    results['data'] = list()

    for result in task_results:
        name = name_cell.render(result=result)
        host = result.host.name
        action = action_link.render(result=result)
        elapsed = time.render(time=result.task.offset_from_playbook)
        duration = time.render(time=result.duration)
        status = task_status_link.render(result=result)

        results['data'].append([name, host, action, elapsed, duration, status])
    return jsonify(results)


@reports.route('/reports/ajax/stats/<playbook>.txt')
def ajax_stats(playbook):
    stats = (models.Stats.query
             .filter(models.Stats.playbook_id.in_([playbook])))
    if not utils.fast_count(stats):
        abort(404)

    jinja = current_app.jinja_env
    host_link = jinja.get_template('ajax/stats.html')

    results = dict()
    results['data'] = list()

    for stat in stats:
        host = host_link.render(stat=stat)
        ok = stat.ok if stat.ok >= 1 else 0
        changed = stat.changed if stat.changed >= 1 else 0
        failed = stat.failed if stat.failed >= 1 else 0
        skipped = stat.skipped if stat.skipped >= 1 else 0
        unreachable = stat.unreachable if stat.unreachable >= 1 else 0

        data = [host, ok, changed, failed, skipped, unreachable]
        results['data'].append(data)

    return jsonify(results)

ara/templates/about.html
{% extends "layout.html" %}

{% block content -%}
<!-- Begin about -->
<div class="container-fluid">
    <div class="col-md-custom col-md-offset-custom">
        <div class="row text-center">
            <br>
            <img src="{{ url_for('static', filename='images/logo-main.svg') }}" width="287" height="226" alt="ARA: Ansible Run Analysis" />
            <h1><strong>ARA - Ansible Run Analysis</strong></h1>
            <h2><a href="https://github.com/openstack/ara" target="_blank">ARA</a> records <a href="https://www.ansible.com/" target="_blank">Ansible</a> playbook runs seamlessly to make them easier to visualize, understand and troubleshoot.</h2>
            <h3>
                ARA doesn't run your playbooks for you: it integrates with Ansible as a callback plugin wherever it is.<br>
                Whether you are running Ansible from your personal laptop, workstation or a server,
                all you need to do is to <a href="https://ara.readthedocs.io/en/latest/installation.html" target="_blank">install ARA</a>,
                <a href="https://ara.readthedocs.io/en/latest/configuration.html">configure Ansible to use ARA</a> and you're good to go.
            </h3>
            <h3>
                The ARA project puts a lot of emphasis on being simple to install and use without requiring you change your existing Ansible workflows.<br>
                You can read about the project's core values and principles in the <a href="https://ara.readthedocs.io/en/latest/manifesto.html">project manifesto</a>.
            </h3>
            <br>
            {% if playbooks and playbooks > 0 -%}
            <h2>ARA makes the following data available:</h2>
            <br>
            <div class="list-group stat-highlight col-md-4 col-md-offset-4">
                <button type="button" class="list-group-item list-group-item-action">
                    <span class="badge">{{ playbooks }}</span>
                    Playbook runs
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    <span class="badge">{{ tasks }}</span>
                    Tasks
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    <span class="badge">{{ task_results }}</span>
                    Task results
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    <span class="badge">{{ hosts }}</span>
                    Hosts
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    <span class="badge">{{ host_facts }}</span>
                    Hosts with gathered facts
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    <span class="badge">{{ files }}</span>
                    Playbook, role and task files
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    <span class="badge">{{ records }}</span>
                    Recorded key/values
                </button>
            </div>
        </div>
        <div class="row text-center">
            <h2>Get started by looking at your <a href="{{ url_for('reports.report_list') }}">playbook reports</a>.</h2>
            {% else -%}
            <h2><strong>The ARA database is empty or the web application is not configured properly to find your playbook data.</strong></h2>
            <h2>Get started by <a href="https://ara.readthedocs.io/en/latest/configuration.html">configuring Ansible to use ARA</a>.</h2>
            <h2>Your data will be available in the interface after an <code>ansible-playbook</code> is run after configuring Ansible to use ARA.</h2>
            <br>
            <br>
            <h3>Need help ? Look at the <a href="https://ara.readthedocs.io/en/latest/">documentation</a> or come chat with users and developers on IRC in #ara on the freenode network.</h3>
            {% endif -%}
        </div>
    </div>
</div>
<br>
<br>
<!-- End about -->
{% endblock %}

ara/templates/file.html
{% include "head.html" %}
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
          <h2>File: <strong>{{ file_.path }}</strong></h2>
          <p>Last updated: {{ file_.playbook.time_end |datefmt }}</p>
          <p>Ansible version: <strong>{{ file_.playbook.ansible_version }}</strong></p>
          {{ file_.content.content | yamlhighlight | safe }}
        </div>
    </div>
</div>
</body>
</html>

ara/templates/file_index.html
{% include "head.html" %}
<!--
This template is not actually served or linked from within the web application.
-->
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>
                    <tr>
                        <th>File</th>
                    </tr>
                </thead>
                <tbody>
                    {% for file in files -%}
                    <tr>
                        <td><a href="{{ url_for('file.show_file', file_=file.id) }}">{{ file.id }}</a></td>
                    </tr>
                    {% endfor -%}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>

ara/templates/head.html
<!DOCTYPE html>
<html class="layout-pf">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ARA | Ansible Run Analysis records Ansible playbook runs seamlessly to make them easier to visualize, understand and troubleshoot">
    <title>ARA | Ansible Run Analysis</title>
    {% block scripts -%}
    <script src="{{ url_for('serve_static_packaged', module='jquery', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('serve_static_packaged', module='datatables', filename='js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('serve_static_packaged', module='bootstrap', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('serve_static_packaged', module='patternfly_bootstrap_treeview', filename='js/bootstrap-treeview.min.js') }}"></script>
    <script src="{{ url_for('serve_static_packaged', module='patternfly', filename='js/patternfly.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/ara.js') }}"></script>
    {% endblock -%}
    {% block stylesheets -%}
    <link href="{{ url_for('serve_static_packaged', module='patternfly', filename='css/patternfly.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('serve_static_packaged', module='patternfly', filename='css/patternfly-additions.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('serve_static_packaged', module='patternfly_bootstrap_treeview', filename='css/bootstrap-treeview.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/pygments.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/ara.css') }}" rel="stylesheet">
    {% endblock -%}
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
</head>

ara/templates/host.html
{% include "head.html" %}
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
          <h2>Host facts: <strong>{{ host.name }}</strong></h2>
          <p>Last updated: {{ host.facts.timestamp |datefmt }}</p>
          <p>Ansible version: <strong>{{ host.playbook.ansible_version }}</strong></p>
          <table class="table table-striped table-bordered table-hover table-condensed">
              <thead>
                  <tr>
                      <th>Fact</th>
                      <th>Value</th>
                  </tr>
              </thead>
              <tbody>
                  {% for fact, value in facts -%}
                  <tr>
                      <td id="{{ fact }}"><a href="#{{ fact }}">{{ fact }}</a></td>
                      <td><pre>{{ value | to_nice_json | safe }}</pre></td>
                  </tr>
                  {% endfor -%}
              </tbody>
          </table>
        </div>
    </div>
</div>
</body>
</html>

ara/templates/host_index.html
{% include "head.html" %}
<!--
This template is not actually served or linked from within the web application.
-->
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>
                    <tr>
                        <th>Host</th>
                    </tr>
                </thead>
                <tbody>
                    {% for host in hosts -%}
                    {% if host.facts -%}
                    <tr>
                        <td><a href="{{ url_for('host.show_host', id=host.id) }}">{{ host.id }}</a></td>
                    </tr>
                    {% endif -%}
                    {% endfor -%}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>

ara/templates/layout.html
{% include "head.html" %}
{% import "macros.html" as macros %}
<body>
{% include "navbar.html" %}

{% block content -%}
{% endblock -%}

</body>
</html>

ara/templates/macros.html
<div id="macros">
{% macro render_status(status) -%}
    {% if status == 'success' -%}
        <span data-toggle="tooltip" data-placement="bottom" title="Playbook completed successfully" class="pficon pficon-ok list-view-pf-icon-sm list-view-pf-icon-success"></span>
    {% elif status == 'failed' -%}
        <span data-toggle="tooltip" data-placement="bottom" title="Playbook completed with errors" class="pficon pficon-error-circle-o list-view-pf-icon-sm list-view-pf-icon-danger"></span>
    {% elif status == 'incomplete' -%}
        <span data-toggle="tooltip" data-placement="bottom" title="Playbook execution is either in progress or was interrupted: data will be inconsistent" class="pficon pficon-info list-view-pf-icon-sm list-view-pf-icon-info"></span>
    {% else -%}
        <span data-toggle="tooltip" data-placement="bottom" title="The status of this playbook is unknown" class="fa fa-question-circle"></span>
    {% endif -%}
{% endmacro -%}

{% macro result_page_length(length) -%}
    {% if length == 0 -%}
        "paging": false,
    {% else -%}
        "pageLength": {{ length }}
    {% endif -%}
{% endmacro -%}
</div>

ara/templates/navbar.html
<!-- Begin navbar -->
<nav class="navbar navbar-default navbar-pf" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('reports.report_list') }}">
            <img src="{{ url_for('static', filename='images/logo-header.svg') }}" width="81" height="32" alt="ARA: Ansible Run Analysis" />
        </a>
    </div>
    <div class="collapse navbar-collapse navbar-collapse-1">
        <ul class="nav navbar-nav navbar-utility">
            <li><a href="https://ara.readthedocs.io/en/latest/" target="_blank">Documentation</a></li>
            <li><a href="https://github.com/openstack/ara" target="_blank"><strong>ARA</strong> {{ ara_version }}</a></li>
            <li><a href="https://www.ansible.com/" target="_blank"><strong>Ansible</strong> {{ ansible_version }}</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-primary">
            {% if (playbooks and playbooks > 0) or playbook -%}
            {% if active and active == 'reports' -%}
            <li class="active">
            {% else -%}
            <li>
            {% endif -%}
                <a href="{{ url_for('reports.report_list') }}">Playbook reports</a>
            </li>
            {% endif -%}
            {% if active and active == 'about' -%}
            <li class="active">
            {% else -%}
            <li>
            {% endif -%}
                <a href="{{ url_for('about.main') }}">About</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End navbar -->

ara/templates/report_list.html
{% extends "layout.html" %}

{% block content -%}
<!-- Begin report list -->
<div class="col-md-custom col-md-offset-custom">
    <div class="row">
        <div class="list-group list-view-pf list-view-pf-view">
            <!-- Begin playbook iteration -->
            {% for playbook in playbooks.items -%}
            {% include "report.html" -%}
            <!-- End playbook iteration -->
            {% endfor -%}
        </div>
    </div>
</div>

<!-- Begin pagination -->
<div class="col-md-11 col-md-offset-custom">
    <div class="row text-center">
        Displaying <strong>{{ playbooks.items |length }}</strong> playbook reports out of a total of <strong>{{ playbooks.total }}</strong>.
    </div>
    {% if playbooks.pages > 1 -%}
    <div class="row text-center">
        <ul class="pagination">
            {% if playbooks.has_prev -%}
            <li>
                <a href="{{ url_for('reports.report_list', page=playbooks.prev_num) }}"><span class="i fa fa-angle-left"></span></a>
            </li>
            {% endif %}
            {% for page in playbooks.iter_pages() -%}
            {% if page == playbooks.page -%}
            <li class="active">
            {% else -%}
            <li>
            {% endif -%}
                <a href="{{ url_for('reports.report_list', page=page) }}">{{ page }}</a>
            </li>
            {% endfor -%}
            {% if playbooks.has_next %}
            <li>
                <a href="{{ url_for('reports.report_list', page=playbooks.next_num) }}"><span class="i fa fa-angle-right"></span></a>
            </li>
            {% endif -%}
        </ul>
    </div>
    {% endif -%}
</div>
<!-- End pagination -->
<!-- End report list -->
{% endblock -%}

ara/templates/report_single.html
{% extends "layout.html" %}

{% block content -%}
<!-- Begin single report -->
<div class="col-md-custom col-md-offset-custom">
    <div class="row">
        <div class="list-group list-view-pf list-view-pf-view">
            {% include "report.html" -%}
        </div>
    </div>
</div>
<!-- End single report -->
{% endblock -%}

ara/templates/task_result.html
{% include "head.html" %}

{% macro display_result(result, hdr) %}
    {% if result is mapping -%}
        {% if 'item' in result -%}
            <{{ hdr }}>Item</{{ hdr }}>
            <pre>{{ result.item |to_nice_json |safe }}</pre>
        {% endif %}

        {% for attr in result.keys()|sort if attr not in ['item', 'changed', 'stdout_lines'] -%}
            {% if result[attr]|default(False) -%}
                <{{ hdr }}>{{ attr|title }}</{{ hdr }}>
                {% if result[attr] is string -%}
                    <pre>{{ result[attr] }}</pre>
                {% elif result[attr] is mapping or result[attr] is iterable -%}
                    <pre>{{ result[attr] |to_nice_json |safe }}</pre>
                {% else -%}
                    <pre>{{ result |to_nice_json |safe }}</pre>
                {% endif -%}
            {% endif -%}
        {% endfor -%}
    {% elif result is iterable and result is not string %}
        {% for item in result -%}
            {% set item = item|from_json %}
            <div class="panel panel-default">
                <div class="panel-body">
                    {{ display_result(item, 'h2') }}
                </div>
            </div>
        {% endfor %}
    {% else -%}
        <pre>{{ result |to_nice_json |safe }}</pre>
    {% endif -%}
{% endmacro %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 results">
          <h2>Task: <strong>{{ task_result.task.name }}</strong></h2>
          {% if task_result.task.tags and task_result.task.tags | from_json | length > 0 -%}
          <h2>Tags: <strong>{{ task_result.task.tags | from_json | join(', ') }}</strong></h2>
          {% endif -%}
          <h2>Host: <strong>{{ task_result.host.name }}</strong></h2>
          <p>Time: <strong>{{ task_result.time_start |datefmt }}</strong></p>
          <p>Ansible version: <strong>{{ task_result.task.playbook.ansible_version }}</strong></p>
          {% set result = task_result.result|from_json %}
          {% if 'results' in result -%}
              {% for item in result.results -%}
                  <h2>Result {{loop.index}}</h2>

                  {{ display_result(item, 'h3') }}
              {% endfor -%}
          {% else -%}
              {{ display_result(result, 'h2') }}
          {% endif -%}
        </div>
    </div>
</div>

ara/templates/task_result_index.html
{% include "head.html" %}
<!--
This template is not actually served or linked from within the web application.
-->
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>
                    <tr>
                        <th>Result</th>
                    </tr>
                </thead>
                <tbody>
                    {% for result in results -%}
                    <tr>
                        <td><a href="{{ url_for('result.show_result', task_result=result.id) }}">{{ result.id }}</a></td>
                    </tr>
                    {% endfor -%}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>